language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t prajwal-wale/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true prajwal-wale/docker-react npm run test